---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: splunk-kubernetes-logging-win
  labels:
    app: splunk-kubernetes-logging-win
    engine: fluentd
    version: 1.2.0
spec:
  template:
    metadata:
      labels:
        app: splunk-kubernetes-logging-win
        version: 1.2.0
      annotations: {}
    spec:
      nodeSelector:
        beta.kubernetes.io/os: windows
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      containers:
      - name: splunk-fluentd-k8s-logs
        image: splunk/fluentd-hec-win:1.1.1  ### change me
        imagePullPolicy: Always
        args:
        - "-c"
        - "/fluentd/etc/fluent.conf"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPLUNK_HEC_TOKEN
          valueFrom:
            secretKeyRef:
              name: splunk-kubernetes-logging
              key: splunk_hec_token
        resources:
          requests:
            cpu: 400m
            memory: 400Mi
        volumeMounts:
        - name: varlog
          mountPath: "C:\\var\\log"
        - name: varlibdockercontainers
          mountPath: "C:\\ProgramData\\docker\\containers"
          readOnly: true
        - name: conf-configmap
          mountPath: "/fluentd/etc"
        - name: secrets
          mountPath: "/fluentd/etc/splunk"
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: "C:\\var\\log"
      - name: varlibdockercontainers
        hostPath:
          path: "C:\\ProgramData\\docker\\containers"
      - name: conf-configmap
        configMap:
          name: splunk-kubernetes-logging
      - name: secrets
        secret:
          secretName: splunk-kubernetes-logging
